name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * 6' # weekly; 08:00 at Saturday

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    if: github.repository == 'hjoshi123/makefile-modules-testing'

    permissions:
      id-token: write

    steps:
      - name: Fail if branch is not head of branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/') && env.SOURCE_BRANCH != '' && env.SELF_UPGRADE_BRANCH != '' }}
        run: |
          echo "This workflow should not be run on a non-branch-head."
          exit 1

      - name: Octo STS Token Exchange
        uses: octo-sts/action@a48df0af0fefd5197a00306a77dd198cdf442a76 # main
        id: octo-sts
        with:
          scope: hjoshi123/makefile-modules-testing
          identity: renovate

      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with:
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@ea850436a5fe75c0925d583c7a02c60a5865461d # v43.0.20
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.octo-sts.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM: "github"
          LOG_LEVEL: "debug"
          RENOVATE_ALLOWED_COMMANDS: '[".*"]'
