name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * 6' # weekly; 08:00 at Saturday

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    if: github.repository == 'hjoshi123/makefile-modules-testing'

    permissions:
      id-token: write

    steps:
      - name: Fail if branch is not head of branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/') && env.SOURCE_BRANCH != '' && env.SELF_UPGRADE_BRANCH != '' }}
        run: |
          echo "This workflow should not be run on a non-branch-head."
          exit 1

      - name: Octo STS Token Exchange
        uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # main
        id: octo-sts
        with:
          scope: hjoshi123/makefile-modules-testing
          identity: renovate

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with:
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@c314dda4a9a93b08239ec978f2043b9a433b9ac4 # v46.3.0
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.octo-sts.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM: "github"
          LOG_LEVEL: "debug"
          RENOVATE_ALLOWED_COMMANDS: '[".*"]'
