name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * 6' # weekly; 08:00 at Saturday

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    if: github.repository == 'hjoshi123/makefile-modules-testing'

    permissions:
      id-token: write

    steps:
      - name: Fail if branch is not head of branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/') && env.SOURCE_BRANCH != '' && env.SELF_UPGRADE_BRANCH != '' }}
        run: |
          echo "This workflow should not be run on a non-branch-head."
          exit 1

      - name: Octo STS Token Exchange
        uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # main
        id: octo-sts
        with:
          scope: hjoshi123/makefile-modules-testing
          identity: renovate

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with:
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@6927a58a017ee9ac468a34a5b0d2a9a9bd45cac3 # v43.0.11
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.octo-sts.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM: "github"
          LOG_LEVEL: "debug"
          RENOVATE_ALLOWED_COMMANDS: '[".*"]'
